<a href="https://colab.research.google.com/github/Welle-Kim/Based-on-the-Review/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
numpy 라이브러리 호출
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
import numpy as np

'''
numpy 버전 출력
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
print(np.__version__)

'''
ndarray 생성
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
data = [10, 20, 30]
arr = np.array(data)

'''
생성한 ndarray 의 속성 출력
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
print('\nCreate 1D Array')
print(arr)
print('type = ', type(arr))
print("shape: {}, size: {}, dtype: {}, dimension: {}"
 .format(arr.shape, arr.size, arr.dtype, arr.ndim))

'''
2차원 ndarray 생성
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
data = [[1,2,3], [4,5,6]]
arr = np.array(data)

'''
생성한 ndarray 의 속성 출력
(아래 주석#을 지우고 결과를 출력해보세요.)
'''
print('\nCreate 2D Array')
print(arr)
print('type = ', type(arr))
print("shape: {}, size: {}, dtype: {}, dimension: {}".format(arr.shape, arr.size, arr.dtype, arr.ndim))

'''
3차원 ndarray 생성
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
data = [[[1, 2, 3],
         [4, 5, 6]],
        [[3, 2, 1],
         [4, 5, 6]]]
arr = np.array(data,dtype=float)

'''
생성한 ndarray 의 속성 출력
(아래 주석#을 지우고 결과를 출력해보세요.)
'''
print('\nCreate 3D Array')
print(arr)
print('type = ', type(arr))
print("shape: {}, size: {}, dtype: {}, dimension: {}".format(arr.shape, arr.size, arr.dtype, arr.ndim))

1.21.6

Create 1D Array
[10 20 30]
type =  <class 'numpy.ndarray'>
shape: (3,), size: 3, dtype: int64, dimension: 1

Create 2D Array
[[1 2 3]
 [4 5 6]]
type =  <class 'numpy.ndarray'>
shape: (2, 3), size: 6, dtype: int64, dimension: 2

Create 3D Array
[[[1. 2. 3.]
  [4. 5. 6.]]

 [[3. 2. 1.]
  [4. 5. 6.]]]
type =  <class 'numpy.ndarray'>
shape: (2, 2, 3), size: 12, dtype: float64, dimension: 3


In [2]:
import numpy as np

def printinfo(arr):
  print(arr)
  print("shape: {}, size: {}, dtype: {}, dimension: {}"
        .format(arr.shape, arr.size, arr.dtype, arr.ndim))

'''
np.arange() 를 통한 ndarray 생성
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
arr = np.arange(2,10)
print('\nCreate ndarray by np.arange()')
printinfo(arr)

'''
np.zeros(data) 를 통한 ndarray 생성1
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
arr = np.zeros(5)
print('\n Create ndarray by np.zeors()')
printinfo(arr)

'''
np.zeros(data, dtype) 를 통한 ndarray 생성2
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
arr = np.zeros((3,4),dtype=int)
print('\n Create ndarray by np.zeors()')
printinfo(arr)

'''
np.ones() 를 통한 ndarray 생성
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
arr =np.ones((3,4))
print('\n Create ndarray by np.ones()')
printinfo(arr)

'''
np.full() 를 통한 ndarray 생성
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
arr =np.full((3,4),77)
print('\n Create ndarray by np.full()')
printinfo(arr)

'''
sample 데이터 생성 및
ones_like() 를 통한 ndarray 생성
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
#sample 데이터 생성
data = [[1,2,3], [4,5,6]]
sample =  np.array(data)
print('\n Sample')
printinfo(sample)

one_array = np.ones_like(sample)
print('\n Create ndarray by np.ones_like()')
printinfo(one_array)


Create ndarray by np.arange()
[2 3 4 5 6 7 8 9]
shape: (8,), size: 8, dtype: int64, dimension: 1

 Create ndarray by np.zeors()
[0. 0. 0. 0. 0.]
shape: (5,), size: 5, dtype: float64, dimension: 1

 Create ndarray by np.zeors()
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
shape: (3, 4), size: 12, dtype: int64, dimension: 2

 Create ndarray by np.ones()
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
shape: (3, 4), size: 12, dtype: float64, dimension: 2

 Create ndarray by np.full()
[[77 77 77 77]
 [77 77 77 77]
 [77 77 77 77]]
shape: (3, 4), size: 12, dtype: int64, dimension: 2

 Sample
[[1 2 3]
 [4 5 6]]
shape: (2, 3), size: 6, dtype: int64, dimension: 2

 Create ndarray by np.ones_like()
[[1 1 1]
 [1 1 1]]
shape: (2, 3), size: 6, dtype: int64, dimension: 2


In [3]:
import numpy as np

# ndarray 속성 출력 함수
def printinfo(arr):
  print(arr)
  print("shape: {}, size: {}, dtype: {}, dimension: {}"
        .format(arr.shape, arr.size, arr.dtype, arr.ndim))
        
# 샘플 데이터 생성
origin_arr = np.arange(15)
print('\nOriginal ndarray')
printinfo(origin_arr)

'''
reshape() 을 활용한 데이터 형상 변경
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
#reshape_arr = np.reshape(origin_arr,(3,6))
#print('\nReshape ndarray')
#printinfo(reshape_arr)

'''
origin_arr에 저장된 1차원 배열을 -1을 활용하여 2차원으로 형상 변경
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
reshape_arr = np.reshape(origin_arr,(3,5))
print('\nReshape(-1, N) to 2D array')
printinfo(reshape_arr)


Original ndarray
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
shape: (15,), size: 15, dtype: int64, dimension: 1

Reshape(-1, N) to 2D array
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
shape: (3, 5), size: 15, dtype: int64, dimension: 2


In [4]:
import numpy as np
import time

# 샘플 데이터 생성
a = np.arange(1,10).reshape(3,3)
print('A---')
print(a)

b = np.arange(9,0,-1).reshape(3,3)
print('\nB---')
print(b)

'''
# NumPy 의 덧셈연산
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
result = a+b
print('\nResult of A + B')
print(result)

result = np.add(a,b)
print('\nResult of np.add(a,b)')
print(result)

'''
# NumPy 의 나눗셈 연산
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
result = a/b
print('\nResult of A / B')
print(result)

result = np.divide(a,b)
print('\nResult of np.divide(a,b)')
print(result)


'''
# NumPy 의 비교연산(>)
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
result = a > b
print('\nResult of comparison operator(>)')
print(result)

'''
# NumPy 의 비교연산(!=)
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
result = a !=b
print('\nResult of comparison operator(!=)')
print(result)

'''
# Python 코드 실행 시간 측정하기
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
python_arr = range(10000000)
start = time.time() 
for i in python_arr:
	i + 1
print("\nPython(ms):", (time.time() - start)*1000) 


'''
# NumPy 코드 실행 시간 측정하기
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
numpy_arr= np.arange(10000000)
start = time.time()
numpy_arr+1
print("NumPy(ms):", (time.time() - start)*1000)

A---
[[1 2 3]
 [4 5 6]
 [7 8 9]]

B---
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Result of A + B
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Result of np.add(a,b)
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Result of A / B
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]

Result of np.divide(a,b)
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]

Result of comparison operator(>)
[[False False False]
 [False False  True]
 [ True  True  True]]

Result of comparison operator(!=)
[[ True  True  True]
 [ True False  True]
 [ True  True  True]]

Python(ms): 1978.9721965789795
NumPy(ms): 63.72404098510742


In [5]:
import numpy as np

# 샘플 데이터 생성
sample = np.arange(1,10).reshape(3,3)
print('Sample')
print(sample)

'''
# axis=None 실습 (default)
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
print('\n[CASE-1]axis=None')
print('sum :',sample.sum() )
print('mean :', sample.mean() )
print('std :', sample.std() )
print('max :', sample.max() )
print('min :', sample.min() )

'''
# axis=0 실습
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
print('\n[CASE-2]axis=0')
print('sum :',sample.sum(axis=0) )
print('mean :', sample.mean(axis=0) )
print('std :', sample.std(axis=0) )
print('max :', sample.max(axis=0) )
print('min :', sample.min(axis=0) )

'''
# axis=1 실습 (default)
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
print('\n[CASE-3]axis=1')
print('sum :',sample.sum(axis=1) )
print('mean :', sample.mean(axis=1) )
print('std :', sample.std(axis=1) )
print('max :', sample.max(axis=1) )
print('min :', sample.min(axis=1) )

Sample
[[1 2 3]
 [4 5 6]
 [7 8 9]]

[CASE-1]axis=None
sum : 45
mean : 5.0
std : 2.581988897471611
max : 9
min : 1

[CASE-2]axis=0
sum : [12 15 18]
mean : [4. 5. 6.]
std : [2.44948974 2.44948974 2.44948974]
max : [7 8 9]
min : [1 2 3]

[CASE-3]axis=1
sum : [ 6 15 24]
mean : [2. 5. 8.]
std : [0.81649658 0.81649658 0.81649658]
max : [3 6 9]
min : [1 4 7]


In [6]:
import numpy as np

'''
# 1차원 샘플 데이터 생성
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
sample = np.arange(5,15)
print('1D-Array Sample:', sample)
print('sample[3] = ',sample[3])

'''
# 인덱싱 값 변경 후 출력
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
sample[3]=0
print('1D-Array Sample:', sample)

'''
# 2차원 샘플 데이터 생성
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
sample = np.arange(16).reshape((4,4))
print('\n2D-Array Indexing')
print(sample)
print('sample[2,3] = ', sample[2,3])


'''
# 인덱싱 값 변경 후 출력
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
sample[2,3]=0
print(sample)

'''
# 3차원 샘플 데이터 생성
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
sample = np.arange(16).reshape((4,2,2))
print('\n3D-Array Indexing')
print(sample)
print('sample[1,1,1] = ', sample[1,1,1])

1D-Array Sample: [ 5  6  7  8  9 10 11 12 13 14]
sample[3] =  8
1D-Array Sample: [ 5  6  7  0  9 10 11 12 13 14]

2D-Array Indexing
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
sample[2,3] =  11
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10  0]
 [12 13 14 15]]

3D-Array Indexing
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]
sample[1,1,1] =  7


In [7]:
import numpy as np

# 1차원 샘플 데이터 생성
sample = np.arange(5,15)
print('1D-Array Sample')
print(sample)

'''
# 슬라이싱 실습
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
print('\nSlicing')
print(sample[2:5])
print(sample[:5])
print(sample[7:])
print(sample[2:-1])       
print(sample[:])

# 2차원 샘플 데이터 생성
sample = np.arange(1,17).reshape(4,4)
print('\n2D-Array Sample')
print(sample)

'''
# 슬라이싱 실습
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
print('\nSlicing')
print(sample[1:3,1:3])
print(sample[:3,0:1])
print(sample[3:,:])
print(sample[:,2])       
print(sample[:,:])

'''
# Negative Index 활용한 슬라이싱 실습
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
print('\nSlicing by Negative Index')
print(sample[:,1:-1])
print(sample[:-1,-2])       
print(sample[:,-1])

1D-Array Sample
[ 5  6  7  8  9 10 11 12 13 14]

Slicing
[7 8 9]
[5 6 7 8 9]
[12 13 14]
[ 7  8  9 10 11 12 13]
[ 5  6  7  8  9 10 11 12 13 14]

2D-Array Sample
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Slicing
[[ 6  7]
 [10 11]]
[[1]
 [5]
 [9]]
[[13 14 15 16]]
[ 3  7 11 15]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Slicing by Negative Index
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
[ 3  7 11]
[ 4  8 12 16]


In [8]:
import numpy as np

# 샘플 데이터 생성
sample = np.array([2,5,8,1])
print('1D-Array Sample')
print(sample)

'''
# np.sort() 정렬
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
result = np.sort(sample)
print('\nResult of np.sort')
print('Result :', result)
print('Original :', sample)

'''
# [::-1] 실습
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
print('\nTest[::-1] ')
print('Original :', sample)
print('Result :',  sample[::-1])

'''
# 내림차순 정렬
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
sort_arr = np.sort(sample)
result = sort_arr[::-1]
print('\nDcending Order')
print('Dcending :', result)

'''
# 샘플 데이터 생성
(아래 주석#을 지우고 코드를 실행하세요.)
'''
sample = np.array([[9,11],[5,1]])
print('\n2D-Array Sample')
print(sample)

'''
# 2차원 배열 정렬 by axis=0
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
result = np.sort(sample,axis=0)
print('\nnp.sort(axis=0) :')
print(result)

'''
# 2차원 배열 정렬 by axis=1
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
result = np.sort(sample,axis=1)
print('\nnp.sort(axis=1) :')
print(result)

'''
# 샘플 데이터 생성
(아래 주석#을 지우고 코드를 실행하세요.)
'''
name = np.array(['John','Samuel','Kate','Mike','Sarah'])
score = np.array([78,84,96,88,82])

'''
# np.argsort() 통해 정렬된 인덱스 값만 반환
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
sort_indexes = np.argsort(score)
print('\nnp.argsort()')
print('sort indexes :', sort_indexes)

'''
# 인덱스 값을 통해 컬럼명 조회
(아래 주석#을 지우고 _____ 란에 실습을 시작하세요.)
'''
print('sort values :', name[sort_indexes])

1D-Array Sample
[2 5 8 1]

Result of np.sort
Result : [1 2 5 8]
Original : [2 5 8 1]

Test[::-1] 
Original : [2 5 8 1]
Result : [1 8 5 2]

Dcending Order
Dcending : [8 5 2 1]

2D-Array Sample
[[ 9 11]
 [ 5  1]]

np.sort(axis=0) :
[[ 5  1]
 [ 9 11]]

np.sort(axis=1) :
[[ 9 11]
 [ 1  5]]

np.argsort()
sort indexes : [0 4 1 3 2]
sort values : ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


###Reference by Codepresso